# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bx/Shannon_C_seq

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bx/Shannon_C_seq

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bx/Shannon_C_seq/CMakeFiles /home/bx/Shannon_C_seq/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bx/Shannon_C_seq/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Shannon_RNASeq_Cpp

# Build rule for target.
Shannon_RNASeq_Cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Shannon_RNASeq_Cpp
.PHONY : Shannon_RNASeq_Cpp

# fast build rule for target.
Shannon_RNASeq_Cpp/fast:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/build
.PHONY : Shannon_RNASeq_Cpp/fast

src/Contig_graph_handler.o: src/Contig_graph_handler.cpp.o
.PHONY : src/Contig_graph_handler.o

# target to build an object file
src/Contig_graph_handler.cpp.o:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/Contig_graph_handler.cpp.o
.PHONY : src/Contig_graph_handler.cpp.o

src/Contig_graph_handler.i: src/Contig_graph_handler.cpp.i
.PHONY : src/Contig_graph_handler.i

# target to preprocess a source file
src/Contig_graph_handler.cpp.i:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/Contig_graph_handler.cpp.i
.PHONY : src/Contig_graph_handler.cpp.i

src/Contig_graph_handler.s: src/Contig_graph_handler.cpp.s
.PHONY : src/Contig_graph_handler.s

# target to generate assembly for a file
src/Contig_graph_handler.cpp.s:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/Contig_graph_handler.cpp.s
.PHONY : src/Contig_graph_handler.cpp.s

src/Contig_handler.o: src/Contig_handler.cpp.o
.PHONY : src/Contig_handler.o

# target to build an object file
src/Contig_handler.cpp.o:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/Contig_handler.cpp.o
.PHONY : src/Contig_handler.cpp.o

src/Contig_handler.i: src/Contig_handler.cpp.i
.PHONY : src/Contig_handler.i

# target to preprocess a source file
src/Contig_handler.cpp.i:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/Contig_handler.cpp.i
.PHONY : src/Contig_handler.cpp.i

src/Contig_handler.s: src/Contig_handler.cpp.s
.PHONY : src/Contig_handler.s

# target to generate assembly for a file
src/Contig_handler.cpp.s:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/Contig_handler.cpp.s
.PHONY : src/Contig_handler.cpp.s

src/Kmer_handler.o: src/Kmer_handler.cpp.o
.PHONY : src/Kmer_handler.o

# target to build an object file
src/Kmer_handler.cpp.o:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/Kmer_handler.cpp.o
.PHONY : src/Kmer_handler.cpp.o

src/Kmer_handler.i: src/Kmer_handler.cpp.i
.PHONY : src/Kmer_handler.i

# target to preprocess a source file
src/Kmer_handler.cpp.i:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/Kmer_handler.cpp.i
.PHONY : src/Kmer_handler.cpp.i

src/Kmer_handler.s: src/Kmer_handler.cpp.s
.PHONY : src/Kmer_handler.s

# target to generate assembly for a file
src/Kmer_handler.cpp.s:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/Kmer_handler.cpp.s
.PHONY : src/Kmer_handler.cpp.s

src/basic_log.o: src/basic_log.cpp.o
.PHONY : src/basic_log.o

# target to build an object file
src/basic_log.cpp.o:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/basic_log.cpp.o
.PHONY : src/basic_log.cpp.o

src/basic_log.i: src/basic_log.cpp.i
.PHONY : src/basic_log.i

# target to preprocess a source file
src/basic_log.cpp.i:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/basic_log.cpp.i
.PHONY : src/basic_log.cpp.i

src/basic_log.s: src/basic_log.cpp.s
.PHONY : src/basic_log.s

# target to generate assembly for a file
src/basic_log.cpp.s:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/basic_log.cpp.s
.PHONY : src/basic_log.cpp.s

src/encoding.o: src/encoding.cpp.o
.PHONY : src/encoding.o

# target to build an object file
src/encoding.cpp.o:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/encoding.cpp.o
.PHONY : src/encoding.cpp.o

src/encoding.i: src/encoding.cpp.i
.PHONY : src/encoding.i

# target to preprocess a source file
src/encoding.cpp.i:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/encoding.cpp.i
.PHONY : src/encoding.cpp.i

src/encoding.s: src/encoding.cpp.s
.PHONY : src/encoding.s

# target to generate assembly for a file
src/encoding.cpp.s:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/encoding.cpp.s
.PHONY : src/encoding.cpp.s

src/local_file_structure.o: src/local_file_structure.cpp.o
.PHONY : src/local_file_structure.o

# target to build an object file
src/local_file_structure.cpp.o:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/local_file_structure.cpp.o
.PHONY : src/local_file_structure.cpp.o

src/local_file_structure.i: src/local_file_structure.cpp.i
.PHONY : src/local_file_structure.i

# target to preprocess a source file
src/local_file_structure.cpp.i:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/local_file_structure.cpp.i
.PHONY : src/local_file_structure.cpp.i

src/local_file_structure.s: src/local_file_structure.cpp.s
.PHONY : src/local_file_structure.s

# target to generate assembly for a file
src/local_file_structure.cpp.s:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/local_file_structure.cpp.s
.PHONY : src/local_file_structure.cpp.s

src/log.o: src/log.cpp.o
.PHONY : src/log.o

# target to build an object file
src/log.cpp.o:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/log.cpp.o
.PHONY : src/log.cpp.o

src/log.i: src/log.cpp.i
.PHONY : src/log.i

# target to preprocess a source file
src/log.cpp.i:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/log.cpp.i
.PHONY : src/log.cpp.i

src/log.s: src/log.cpp.s
.PHONY : src/log.s

# target to generate assembly for a file
src/log.cpp.s:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/log.cpp.s
.PHONY : src/log.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Shannon_RNASeq_Cpp.dir/build.make CMakeFiles/Shannon_RNASeq_Cpp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Shannon_RNASeq_Cpp"
	@echo "... src/Contig_graph_handler.o"
	@echo "... src/Contig_graph_handler.i"
	@echo "... src/Contig_graph_handler.s"
	@echo "... src/Contig_handler.o"
	@echo "... src/Contig_handler.i"
	@echo "... src/Contig_handler.s"
	@echo "... src/Kmer_handler.o"
	@echo "... src/Kmer_handler.i"
	@echo "... src/Kmer_handler.s"
	@echo "... src/basic_log.o"
	@echo "... src/basic_log.i"
	@echo "... src/basic_log.s"
	@echo "... src/encoding.o"
	@echo "... src/encoding.i"
	@echo "... src/encoding.s"
	@echo "... src/local_file_structure.o"
	@echo "... src/local_file_structure.i"
	@echo "... src/local_file_structure.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

